// Vocabulário oficial do HSK 1 — 150 palavras.
// Campos: hanzi (caractere), pinyin (com marcas de tom) e translation (português).
export const HSK1 = [
  { hanzi: '爱', pinyin: 'ài', translation: 'amar' },
  { hanzi: '八', pinyin: 'bā', translation: 'oito' },
  { hanzi: '爸爸', pinyin: 'bàba', translation: 'pai' },
  { hanzi: '杯子', pinyin: 'bēizi', translation: 'copo' },
  { hanzi: '北京', pinyin: 'Běijīng', translation: 'Pequim' },
  { hanzi: '本', pinyin: 'běn', translation: 'classificador (para livros)' },
  { hanzi: '不', pinyin: 'bù', translation: 'não' },
  { hanzi: '不客气', pinyin: 'bú kèqi', translation: 'de nada' },
  { hanzi: '菜', pinyin: 'cài', translation: 'prato / comida' },
  { hanzi: '茶', pinyin: 'chá', translation: 'chá' },
  { hanzi: '吃', pinyin: 'chī', translation: 'comer' },
  { hanzi: '出租车', pinyin: 'chūzūchē', translation: 'táxi' },
  { hanzi: '打电话', pinyin: 'dǎ diànhuà', translation: 'telefonar' },
  { hanzi: '大', pinyin: 'dà', translation: 'grande' },
  { hanzi: '的', pinyin: 'de', translation: 'partícula possessiva' },
  { hanzi: '点', pinyin: 'diǎn', translation: 'hora (do relógio) / ponto' },
  { hanzi: '电脑', pinyin: 'diànnǎo', translation: 'computador' },
  { hanzi: '电视', pinyin: 'diànshì', translation: 'televisão' },
  { hanzi: '电影', pinyin: 'diànyǐng', translation: 'filme' },
  { hanzi: '东西', pinyin: 'dōngxi', translation: 'coisa' },
  { hanzi: '都', pinyin: 'dōu', translation: 'todos / ambos' },
  { hanzi: '读', pinyin: 'dú', translation: 'ler' },
  { hanzi: '对不起', pinyin: 'duìbuqǐ', translation: 'desculpe' },
  { hanzi: '多', pinyin: 'duō', translation: 'muito' },
  { hanzi: '多少', pinyin: 'duōshao', translation: 'quanto(s)' },
  { hanzi: '儿子', pinyin: 'érzi', translation: 'filho' },
  { hanzi: '二', pinyin: 'èr', translation: 'dois' },
  { hanzi: '饭店', pinyin: 'fàndiàn', translation: 'restaurante / hotel' },
  { hanzi: '飞机', pinyin: 'fēijī', translation: 'avião' },
  { hanzi: '分钟', pinyin: 'fēnzhōng', translation: 'minuto' },
  { hanzi: '高兴', pinyin: 'gāoxìng', translation: 'feliz / contente' },
  { hanzi: '个', pinyin: 'gè', translation: 'classificador geral' },
  { hanzi: '工作', pinyin: 'gōngzuò', translation: 'trabalho / trabalhar' },
  { hanzi: '狗', pinyin: 'gǒu', translation: 'cachorro' },
  { hanzi: '汉语', pinyin: 'Hànyǔ', translation: 'língua chinesa (mandarim)' },
  { hanzi: '好', pinyin: 'hǎo', translation: 'bom' },
  { hanzi: '号', pinyin: 'hào', translation: 'número / dia (data)' },
  { hanzi: '喝', pinyin: 'hē', translation: 'beber' },
  { hanzi: '和', pinyin: 'hé', translation: 'e / com' },
  { hanzi: '很', pinyin: 'hěn', translation: 'muito' },
  { hanzi: '后面', pinyin: 'hòumiàn', translation: 'atrás' },
  { hanzi: '回', pinyin: 'huí', translation: 'voltar / retornar' },
  { hanzi: '会', pinyin: 'huì', translation: 'saber (fazer) / poder' },
  { hanzi: '火车站', pinyin: 'huǒchēzhàn', translation: 'estação de trem' },
  { hanzi: '几', pinyin: 'jǐ', translation: 'quanto(s)' },
  { hanzi: '家', pinyin: 'jiā', translation: 'casa / família' },
  { hanzi: '叫', pinyin: 'jiào', translation: 'chamar(-se)' },
  { hanzi: '今天', pinyin: 'jīntiān', translation: 'hoje' },
  { hanzi: '九', pinyin: 'jiǔ', translation: 'nove' },
  { hanzi: '开', pinyin: 'kāi', translation: 'abrir / ligar' },
  { hanzi: '看', pinyin: 'kàn', translation: 'olhar / ver' },
  { hanzi: '看见', pinyin: 'kànjiàn', translation: 'avistar / ver' },
  { hanzi: '块', pinyin: 'kuài', translation: 'unidade monetária (yuan)' },
  { hanzi: '来', pinyin: 'lái', translation: 'vir' },
  { hanzi: '老师', pinyin: 'lǎoshī', translation: 'professor(a)' },
  { hanzi: '了', pinyin: 'le', translation: 'partícula de aspecto' },
  { hanzi: '冷', pinyin: 'lěng', translation: 'frio' },
  { hanzi: '里', pinyin: 'lǐ', translation: 'dentro / em' },
  { hanzi: '六', pinyin: 'liù', translation: 'seis' },
  { hanzi: '妈妈', pinyin: 'māma', translation: 'mãe' },
  { hanzi: '吗', pinyin: 'ma', translation: 'partícula interrogativa' },
  { hanzi: '买', pinyin: 'mǎi', translation: 'comprar' },
  { hanzi: '猫', pinyin: 'māo', translation: 'gato' },
  { hanzi: '没关系', pinyin: 'méi guānxi', translation: 'não tem problema' },
  { hanzi: '没有', pinyin: 'méiyǒu', translation: 'não ter / não haver' },
  { hanzi: '米饭', pinyin: 'mǐfàn', translation: 'arroz cozido' },
  { hanzi: '名字', pinyin: 'míngzi', translation: 'nome' },
  { hanzi: '明天', pinyin: 'míngtiān', translation: 'amanhã' },
  { hanzi: '哪', pinyin: 'nǎ', translation: 'qual' },
  { hanzi: '哪儿', pinyin: 'nǎr', translation: 'onde' },
  { hanzi: '那', pinyin: 'nà', translation: 'aquele / aquilo' },
  { hanzi: '呢', pinyin: 'ne', translation: 'partícula interrogativa' },
  { hanzi: '能', pinyin: 'néng', translation: 'poder / conseguir' },
  { hanzi: '你', pinyin: 'nǐ', translation: 'você' },
  { hanzi: '年', pinyin: 'nián', translation: 'ano' },
  { hanzi: '女儿', pinyin: "nǚ'ér", translation: 'filha' },
  { hanzi: '朋友', pinyin: 'péngyou', translation: 'amigo(a)' },
  { hanzi: '漂亮', pinyin: 'piàoliang', translation: 'bonito(a)' },
  { hanzi: '苹果', pinyin: 'píngguǒ', translation: 'maçã' },
  { hanzi: '七', pinyin: 'qī', translation: 'sete' },
  { hanzi: '前面', pinyin: 'qiánmiàn', translation: 'à frente / na frente' },
  { hanzi: '钱', pinyin: 'qián', translation: 'dinheiro' },
  { hanzi: '请', pinyin: 'qǐng', translation: 'por favor / convidar' },
  { hanzi: '去', pinyin: 'qù', translation: 'ir' },
  { hanzi: '热', pinyin: 'rè', translation: 'quente' },
  { hanzi: '人', pinyin: 'rén', translation: 'pessoa' },
  { hanzi: '认识', pinyin: 'rènshi', translation: 'conhecer' },
  { hanzi: '三', pinyin: 'sān', translation: 'três' },
  { hanzi: '商店', pinyin: 'shāngdiàn', translation: 'loja' },
  { hanzi: '上', pinyin: 'shàng', translation: 'em cima / subir' },
  { hanzi: '上午', pinyin: 'shàngwǔ', translation: 'manhã (período)' },
  { hanzi: '少', pinyin: 'shǎo', translation: 'pouco' },
  { hanzi: '谁', pinyin: 'shéi', translation: 'quem' },
  { hanzi: '什么', pinyin: 'shénme', translation: 'o que / qual' },
  { hanzi: '十', pinyin: 'shí', translation: 'dez' },
  { hanzi: '时候', pinyin: 'shíhou', translation: 'momento / quando' },
  { hanzi: '是', pinyin: 'shì', translation: 'ser / sim' },
  { hanzi: '书', pinyin: 'shū', translation: 'livro' },
  { hanzi: '水', pinyin: 'shuǐ', translation: 'água' },
  { hanzi: '水果', pinyin: 'shuǐguǒ', translation: 'fruta' },
  { hanzi: '睡觉', pinyin: 'shuìjiào', translation: 'dormir' },
  { hanzi: '说话', pinyin: 'shuōhuà', translation: 'falar' },
  { hanzi: '四', pinyin: 'sì', translation: 'quatro' },
  { hanzi: '岁', pinyin: 'suì', translation: 'anos (de idade)' },
  { hanzi: '他', pinyin: 'tā', translation: 'ele' },
  { hanzi: '她', pinyin: 'tā', translation: 'ela' },
  { hanzi: '太', pinyin: 'tài', translation: 'demais / muito' },
  { hanzi: '天气', pinyin: 'tiānqì', translation: 'tempo / clima' },
  { hanzi: '听', pinyin: 'tīng', translation: 'ouvir / escutar' },
  { hanzi: '同学', pinyin: 'tóngxué', translation: 'colega de classe' },
  { hanzi: '喂', pinyin: 'wéi', translation: 'alô (ao telefone)' },
  { hanzi: '我', pinyin: 'wǒ', translation: 'eu' },
  { hanzi: '我们', pinyin: 'wǒmen', translation: 'nós' },
  { hanzi: '五', pinyin: 'wǔ', translation: 'cinco' },
  { hanzi: '喜欢', pinyin: 'xǐhuan', translation: 'gostar' },
  { hanzi: '下', pinyin: 'xià', translation: 'embaixo / descer' },
  { hanzi: '下午', pinyin: 'xiàwǔ', translation: 'tarde (período)' },
  { hanzi: '下雨', pinyin: 'xiàyǔ', translation: 'chover' },
  { hanzi: '先生', pinyin: 'xiānsheng', translation: 'senhor' },
  { hanzi: '现在', pinyin: 'xiànzài', translation: 'agora' },
  { hanzi: '想', pinyin: 'xiǎng', translation: 'querer / pensar' },
  { hanzi: '小', pinyin: 'xiǎo', translation: 'pequeno' },
  { hanzi: '小姐', pinyin: 'xiǎojiě', translation: 'senhorita' },
  { hanzi: '些', pinyin: 'xiē', translation: 'alguns / um pouco' },
  { hanzi: '写', pinyin: 'xiě', translation: 'escrever' },
  { hanzi: '谢谢', pinyin: 'xièxie', translation: 'obrigado(a)' },
  { hanzi: '星期', pinyin: 'xīngqī', translation: 'semana' },
  { hanzi: '学生', pinyin: 'xuésheng', translation: 'estudante' },
  { hanzi: '学习', pinyin: 'xuéxí', translation: 'estudar / aprender' },
  { hanzi: '学校', pinyin: 'xuéxiào', translation: 'escola' },
  { hanzi: '一', pinyin: 'yī', translation: 'um' },
  { hanzi: '衣服', pinyin: 'yīfu', translation: 'roupa' },
  { hanzi: '医生', pinyin: 'yīshēng', translation: 'médico(a)' },
  { hanzi: '医院', pinyin: 'yīyuàn', translation: 'hospital' },
  { hanzi: '椅子', pinyin: 'yǐzi', translation: 'cadeira' },
  { hanzi: '有', pinyin: 'yǒu', translation: 'ter / haver' },
  { hanzi: '月', pinyin: 'yuè', translation: 'mês / lua' },
  { hanzi: '在', pinyin: 'zài', translation: 'estar (em) / em' },
  { hanzi: '再见', pinyin: 'zàijiàn', translation: 'até logo / tchau' },
  { hanzi: '怎么', pinyin: 'zěnme', translation: 'como' },
  { hanzi: '怎么样', pinyin: 'zěnmeyàng', translation: 'que tal / como está' },
  { hanzi: '这', pinyin: 'zhè', translation: 'este / isto' },
  { hanzi: '中国', pinyin: 'Zhōngguó', translation: 'China' },
  { hanzi: '中午', pinyin: 'zhōngwǔ', translation: 'meio-dia' },
  { hanzi: '住', pinyin: 'zhù', translation: 'morar / residir' },
  { hanzi: '桌子', pinyin: 'zhuōzi', translation: 'mesa' },
  { hanzi: '字', pinyin: 'zì', translation: 'caractere / palavra' },
  { hanzi: '昨天', pinyin: 'zuótiān', translation: 'ontem' },
  { hanzi: '坐', pinyin: 'zuò', translation: 'sentar / tomar (transporte)' },
  { hanzi: '做', pinyin: 'zuò', translation: 'fazer' },
];
